[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["cd Backend && python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd Backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
