[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
	"python3 -m venv /opt/venv",
	"/opt/venv/bin/pip install -r Backend/requirements.txt"
]

[start]
cmd = "/opt/venv/bin/uvicorn main:app --app-dir Backend --host 0.0.0.0 --port $PORT"
