[build]
builder = "NIXPACKS"
buildCommand = "cd Backend && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "cd Backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
